language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run cov
env:
  global:
    # FIREBASE_TOKEN
    - secure: TovnJSi+FFzgPW+7zToTb7TjTVmvNj3UnHsRzL5fu3ROpoYNbt3fZViPBW1aZp8dllWqBm2t2VbTbGa6cruGqeZVe8wGD4KKnCl2IFJ326ex6Q8TxO9ewQQ0D6UWuHTIB/t52DuEtoEsDI4ptBwc5Xi9RJCkIJ41Bu1n79G2q2WTJhyNtPg6ERrup4vBEvoZqVRQpAI4Wg7Vkbr7ONRjPWUsBhsIWeARIgFdwgjU5GMVLPLuENVTsfxRtbjmNWIDErU8HhHyz3pg0sHBw2Nn5E2kTjT01ncii3rHhOkZ996nGTK9beOlGGp+BfmQb2RWr3XV5vWjHJxu4p3LOzyh2FLWR5/4EErG21y1a3quWoFq2ddMJui6ZNa8dv99YHTQj81P+pwFFsQUf/IJBk7jzSdNpNF/MJQnJvVw8R1i+wiV7DspPPZG2u10xvTjfqDPHvsx0uvqNWduZYIt/x+v6ZCRs16sfzWslrJRGy8knccPGp9QcbrVjtq68o+T1ZcNZyTXewlYVmE4zO9+qn3qu6e5i7G46lUe4fQdpOHxRTVWGcjEw8NYzSw3HLb03Ukhz95fs19FNhloctmL71CwrCw1ZXwL4aCcqNwgYQqmMmkxnyAXEYhP09wrteEI24armlu8hFXpSMsgDrDb/Q7q7bSMKc69EcFmS2GJbHqwvb0=
    # FIREBASE_SECRET
    - secure: atHbMOtbRHOq3LYl4azJX3jW8n+oGF8ofI4V+AOUYVvW6JANShbeJmfehzlk///TWKB2X/VErUdlVF3l7kRUn2wzW0nk4crrKM0gddHBPCh7kQNRhNd4+fIucE9QwGJ4wfpcqXWQCGss2V8zRPXms2c9VcFtDgReuhW9tSnp73nkHGRDKfIiB/wRGjr0zlkkU3OGOJGOgFuxdUiXkTBk4+lfgm4pLCrNYy9lbjcyINib1iiFBFjJjVPdLsE4Ny/8JAkfpewX5d3NlGqanZMYeRPb2qnUv/Lgrum1LW/Nk3RsDgI+LrljShhXkHCNIdk5Gls2uR4Q/JmXmFZxQO1vHF71HCB5riepragzmAYL/scNjkWRviuxxfQDs5eS9X9DT+Xu2YRf38JpQEwZQB6KWnrrI8LobRrFwkWWX2ZlJG6k87VH0y0gqjBXez0dUEOVX9Dfkf5XfyNIylQPbmD3X8uGiehDcRSuHWnloW4fEZlHVIpVnFZUpJ6kmHjBPDGKeQcFPChM396wseSJuTgGOD9IwZte03LXkyoi7W8f7isoYfdD2DdUDHG6fwEsFpW2ec8I6xYZmX9T3ZZNrZ076PmkVnU9QGDu9LAfPgbuU5rFiJT8hKgd7NWsJzfMcNotrF1AEOxQiAhE8td4HreCvZT/3otJ94FbNKI/sr+I6EU=
